version: "3.8"

services:
  pygame-app:
    build: .
    container_name: pygame-pond
    environment:
      - DISPLAY=host.docker.internal:0  # Update this for Windows
      - XAUTHORITY=/tmp/.docker.xauth
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=pond_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - MQTT_BROKER=mqtt-broker
      - MQTT_PORT=1883
      - XDG_RUNTIME_DIR=/tmp/runtime-root  # Add this line
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
    depends_on:
      - postgres
      - mqtt-broker
    networks:
      - pond-network

  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pond_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - pond-network

  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: mqtt-broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - mqtt-data:/mosquitto/data
      - mqtt-log:/mosquitto/log
    networks:
      - pond-network

networks:
  pond-network:
    driver: bridge

volumes:
  postgres-data:
  mqtt-data:
  mqtt-log:
